### ISSUE TITLE
Audio locks up after repeated calls to play sfx

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf-mc#35] opened 2016-04-30 02:47 UTC
Sound player events result in this:
WARNING : kivy : Track: All internal audio events are currently in use, could not play sound sling_bounce

- after triggering the slings multiple times (I assume more than 8 times within the length of the sample)

Config:
sound_system:
  buffer: 4096
  frequency: 44100
  channels: 2
  master_volume: 0.9
  tracks:
    voice:
      volume: 0.6
      simultaneous_sounds: 1
      preload: yes
    sfx:
      volume: 0.4
      simultaneous_sounds: 8
      preload: yes
    music:
      volume: 0.5
      simultaneous_sounds: 1

assets:
    sounds:
        default:
            load: preload
        voice:
            load: preload
            track: voice
        sfx:
            load: preload
            track: sfx
        music:
            load: on_demand
            track: music
            
sounds:
    sling_bounce:
        track: sfx
        
        
sound_player:
  sw_sling: sling_bounce

**Comment by qcapen** [comment] 2016-04-30 04:38
This bug is caused by not processing several triggered internal audio events (event_sound_started and event_sound_stopped).  These events were getting created, but never processed causing the internal sound events to become all used.  The solution is to properly process all events in the audio interface tick function and reset events once they have been processed.  This had nothing to do with the number of simultaneous sounds set for each track.

**Comment by qcapen** [comment] 2016-04-30 04:42
The bug is actually triggered much faster than 32 sounds played as several internal events are actually triggered when each sound is played.

**Comment by qcapen** [comment] 2016-04-30 04:45
Time to create some additional methods to support better audio tests so I can write a test for this before fixing it.

**Comment by qcapen** [comment] 2016-05-06 18:57
Should be fixed now

**Closed by qcapen** 2016-05-06 18:57 UTC
Labels: bug, in progress
