### ISSUE TITLE
Sound Player hangs

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#222] opened 2016-12-18 13:44 UTC
2016-12-18 13:36:05,255 : DEBUG : Track.1.TrackStandard.music : Next pending sound in queue is still loading, re-queueing sound <SoundInstance: skillshot_theme (119508160), Volume=0.75, Loops=0, Priority=600, Loaded=False, Track=music>

From: https://groups.google.com/forum/m/#!topic/mpf-users/PUm82TNTlF0

**Comment by qcapen** [comment] 2016-12-19 04:03
This problem is caused by Gstreamer hanging while attempting to load some ogg vorbis files.  When the problem ogg files are converted to wav files, the problem goes away.  Still looking for a way to detect the situation or work around it.  More research and testing is warranted.

**Comment by qcapen** [comment] 2016-12-20 20:40
This problem is proving to be much more complicated than first thought.  Rather than a problem with specific ogg vorbis files, this problem appears to be some kind of a deadlock (perhaps involving the GIL) that occurs when an ogg vorbis sound file (or sound file other than wav format) is loading while a video clip is playing in the MC. I am currently working on writing a test to repeatedly reproduce the issue before digging in to finding a solution.

There are two temporary work-arounds: 1) use wav files (which don't use gstreamer to load), or 2) use 'preload' with your sounds (not 'on-demand') so all sounds are loaded into memory at the beginning before playing any videos.

**Comment by qcapen** [comment] 2017-01-08 18:55
I now have a test to reproduce this issue and now fully understand the problem.  Basically, the sound loader that uses gstreamer (all sound file formats other than wav), will block the media controller while it is loading.  It is not really noticeable with very short sounds, but stops all output and appears to hang while loading longer sounds (such as music tracks).  The solution will be to use threading and non-blocking calls for the gstreamer sound loader.  Now that I finally fully understand the issue I should be able to develop a solution in the next week or so.

In the meantime, there are three work-arounds:

1) Use wav files (which don't use gstreamer to load)
2) Use 'preload' with your sounds (not 'on-demand') so all sounds are loaded into memory at the beginning before the game/attract mode begins
3) Use sound streaming for larger sounds ('streaming: True') to stream the sounds from disk rather than loading into memory.

**Comment by qcapen** [comment] 2017-02-10 15:10
Have addressed this issue in 0.33 by removing the gstreamer sound loader and replacing it with sdl_mixer to load sounds into memory.  This is similar to the code in 0.32.  The downside is the MPFMC has to open an extra audio output device to support both SDL2 and SDL_Mixer simultaneously.  The SDL_Mixer output is not used at all, but must be kept open. If this becomes problematic on any platform, it will be possible to use the sdl_mixer callback functions for all audio processing and eliminate the SDL2 output.

**Comment by qcapen** [comment] 2017-02-26 14:32
A PR that resolves this issue was created two weeks ago, but is waiting to be tested on the Mac before it is merged.  Stay tuned...  @toomanybrians: can you test this (especially the installation) on the Mac and merge the PR if all is well (restore-sdl-mixer-sound-loader branch, PR #239 )?

**Closed as completed** 2017-02-27 17:28 UTC
Labels: bug
